### ISSUE TITLE
USER STORY: View recipes on home page

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#10]
As a **user** I can **view recipes on the home page** so that **I can browse through them and find any that interest me**

### Acceptance Criteria:
* Acceptance Criteria 1: The recipes should display as a list on the home page
* Acceptance Criteria 2: The recipes should provide a picture and basic summary of the recipe
* Acceptance Criteria 3: The recipes should be styled displayed in an appealing way 

### Tasks:
- [x] Add RecipeList class view to views.py with logic and queryset for recipes
- [x] Add URL path for the RecipeList view to urls.py
- [x] Create index/homepage template with content, logic and styling
- [x] Create base template with header and footer navigation
- [x] Add links to homepage in base template navigation menus
- [x] Test functionality
