### ISSUE TITLE
USER STORY: Food type categories

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#14]
As a **user** I can **view recipes categorised by food type on the home page** so that **I can easily locate a certain type of food and reduce the time I spend looking through recipes that I'm not interested in**

### Acceptance Criteria:
* Acceptance Criteria 1: The home page should display food category sections
* Acceptance Criteria 2: Each section will display a list of recipes grouped by food types 
* Acceptance Criteria 3: Each section should display a maximum of six recipes

### Tasks:
- [x] Add category array field to Recipe model in models.py 
- [x] Add custom category choices to array field 
- [x] Add modified array field class to allow for multiple checkboxes on forms
- [x] Add field into RecipeForm in forms.py
- [ ] Amend RecipeList class view to include multiple food category querysets
- [ ] Add food category sections with styling and logic into the index template
- [ ] Test functionality
