### ISSUE TITLE
USER STORY: Search for recipe or category

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#15]
As a **user** I can **search the site for a particular word or phrase** so that **I can find a recipe or category of food I'm looking for**

### Acceptance Criteria:
* Acceptance Criteria 1: A search form field should appear on the home page
* Acceptance Criteria 2: The field should allow a user to input a word or group of words
* Acceptance Criteria 3: Submitting the form field should bring the user to a search page that displays a list of recipes or categories that match the search query
* Acceptance Criteria 4: The user should then be able to click one of the options displayed to navigate to the relevant page or click the back button to navigate back to the home page

### Tasks:
- [ ] Add SearchRecipe class view with logic into views.py
- [ ] Add URL path for SearchRecipe view into urls.py
- [ ] Create template for search_recipe with content, logic and styling
- [ ] Add SearchRecipe form into forms.py 
- [ ] Add form with styling and logic into the index template
- [ ] Test functionality
