### ISSUE TITLE
USER STORY: View full recipe details

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#18]
As a **user** I can **click on a recipe link on the home page and be directed to a full page for the recipe** so that **I can see the full recipe details and find out more information**

### Acceptance Criteria:
* Acceptance Criteria 1: A user should be able to click on any recipe displayed on the home page and be redirected to that recipes full page recipe details
* Acceptance Criteria 2: The page should feature the recipes full details as well as a back button to navigate the user back to the home page

### Tasks:
- [x] Add RecipeDetails class view with logic to views.py
- [x] Add URL path RecipeDetails in urls.py 
- [x] Create recipe_details template with content and logic 
- [x] Add URL links to recipe_details to each recipe on the index template, as well as the my_favourites template and all recipes that are published on the my_recipes template
- [x] Test functionality
