### ISSUE TITLE
USER STORY: View recipe prep and cooking times

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#20]
As a **user** I can **see the preparation and approximate cooking times for all recipes** so that **I can asses what recipes are right for me and plan my cooking time**

### Acceptance Criteria:
* Acceptance Criteria 1: Post a recipe forms should have required preparation and approximate cooking time number fields 
* Acceptance Criteria 2: Preparation and approximate cooking times should display on the full recipe page details 
* Acceptance Criteria 3: The cooking and preparation times should display as coloured badges 

### Tasks:
- [x] Add prep_time field and cooking_time field to Recipe model
- [x] Add fields to RecipeForm in forms.py
- [x] Add recipe prep time and cooking time tags to recipe_details template 
- [x] Add content and styling for recipe prep time and cooking time to recipe_details template
- [x] Test functionality
