### ISSUE TITLE
USER STORY: Recipe difficulty rating

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#21]
As a **user** I can **see a difficulty rating for each recipe** so that **I can quickly tell if a recipe is too difficult for me**

### Acceptance Criteria:
* Acceptance Criteria 1: Post a recipe forms should display required select fields for easy, medium, hard or expert
* Acceptance Criteria 2: The difficulty rating should appear on every recipe as a coloured label
* Acceptance Criteria 3: Difficulty ratings should appear on all recipes on the home page as well as the individual recipe details pages

### Tasks:
- [x] Add difficulty field to Recipe model
- [x] Add custom difficulties choices to field options
- [x] Add difficulty field to RecipeForm in forms.py
- [x] Add recipe difficulty tag to recipe_details template with logic
- [x] Add content and styling for recipe difficulty to recipe_details template
- [x] Test functionality
