### ISSUE TITLE
USER STORY: Recipe serving number

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#22]
As a **user** I can **see the approximate amount of people that the recipes can serve** so that **I can easily adjust the ingredient amounts to match the number of people I am cooking for**

### Acceptance Criteria:
* Acceptance Criteria 1: The post a recipe form should have a required serving number field
* Acceptance Criteria 2: The serving number should appear on the details page for every recipe
* Acceptance Criteria 3: The serving number should appear in a coloured label 

### Tasks:
- [x] Add serves field to Recipe model
- [x] Add serves field to RecipeForm in forms.py
- [x] Add recipe serves tag to recipe_details template 
- [x] Add content and styling for recipe serves to recipe_details template
- [x] Test functionality
