### ISSUE TITLE
USER STORY: View recipe allergens

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#23]
As a **user** I can **see a list of allergens for the recipes** so that **I can avoid any recipes that contain certain allergens**

### Acceptance Criteria:
* Acceptance Criteria 1: The post a recipe form should contain a required tick-box field for allergens
* Acceptance Criteria 2: The allergens for each recipe should be displayed on the individual recipe full details pages
* Acceptance Criteria 3: The allergens should all be displayed in an easy to view list format which is clearly displayed

### Tasks:
- [x] Add allergens array field to Recipe model
- [x] Add model method string_of_allergens to return a string of the allergens array field 
- [x] Add custom array field class to allow multiple checkbox inputs
- [x] Add allergens field to RecipeForm in forms.py
- [x] Add recipe allergens tag to recipe_details template 
- [x] Add content and styling for recipe allergens to recipe_details template
- [x] Test functionality
