### ISSUE TITLE
USER STORY: View recipe ingredients

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#24]
As a **user** I can **see a summarised list of ingredients for each recipe** so that **I can quickly and easily read through the ingredients to get an idea of the amounts required**

### Acceptance Criteria:
* Acceptance Criteria 1: Post a recipe forms should have a required text field for an unordered list of ingredients and amounts with visual instructions on how to format the text
* Acceptance Criteria 2: Full ingredient lists should be displayed on each recipe's full details page
* Acceptance Criteria 3: The ingredients should be displayed as an unordered list with nicely formatted spacing and margins to make them easy to read

### Tasks:
- [x] Add ingredients field to Recipe model
- [x] Add ingredients field to RecipeForm in forms.py
- [x] Import summernote to RecipeForm and add widget to field
- [x] Add recipe ingredients tag to recipe_details template 
- [x] Add content and styling for recipe ingredients to recipe_details template
- [x] Test functionality
