### ISSUE TITLE
USER STORY: Like a recipe

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#34]
As a **user** I can **like a recipe** so that **I can view that recipe in the recipe list on my 'my favourites' page at a later date**

### Acceptance Criteria:
* Acceptance Criteria 1: A heart icon should appear next to each recipe on the home page as well as on the individual recipe details pages
* Acceptance Criteria 2: The heart icon should only function if a user is logged in
* Acceptance Criteria 3: If a user clicks the heart icon when not logged in the icon doesn't change
* Acceptance Criteria 4: If a user clicks the heart icon when logged in the page should refresh and an alert should be displayed to the user that the recipe has been added to the 'my favourites' page
* Acceptance Criteria 5: When active, the heart icon should change colour to display that the recipe has been liked

### Tasks:
- [x] Add likes many-to-many field into Recipe model
- [x] Add RecipeLike view to views.py
- [x] Add URL for RecipeLike to urls.py
- [x] Add links to RecipeLike to recipe_details template
- [x] Test functionality
