### ISSUE TITLE
USER STORY: Unlike a recipe

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#35]
As a **user** I can **unlike a recipe** so that **I can remove the recipe list on the 'my favourites' page**

### Acceptance Criteria:
* Acceptance Criteria 1: A user should be able to unlike a recipe by clicking the heart icon next to the recipe
* Acceptance Criteria 2: This functionality should only be available to users who are logged in
* Acceptance Criteria 3: When a user clicks the heart icon of a recipe which is already liked, the current page should be refreshed and an alert should be displayed to the user that the recipe has been removed from the 'my favourites' page
* Acceptance Criteria 4: The icon should return back to its original colour to signify it is no longer liked
* Acceptance Criteria 5: This functionality should also be available from the 'my favourites' page

### Tasks:
- [x] Add UnlikeRecipe view with logic to views.py
- [x] Add path for UnlikeRecipe view in urls.py
- [x] Add links into my_favourites template
- [x] Test functionality
