### ISSUE TITLE
USER STORY: Update account profile image

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#4]
As a **user** I can **add a profile image to my account** so that **I can make my profile my personal **

### Acceptance Criteria:
* Acceptance Criteria 1: An 'update profile picture' button should appear on the user account details page
* Acceptance Criteria 2: The button should open a pop-up window where the user can upload an image from their computer
* Acceptance Criteria 3: The profile picture should update on the users profile

### Tasks:
- [ ] Add profile picture cloudinary field to extended user model in models.py
- [ ] Add profile picture field into EditAccountDetails form in forms.py
- [ ] Add logic for form into AccountDetails view in views.py
- [ ] Add form functionality to account_details template with styling
- [ ] Test functionality
