### ISSUE TITLE
USER STORY: Admin: Add featured recipe

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#42]
As an **admin** I can **make a recipe featured** so that **the recipe can be viewed as the featured recipe on the home page**

### Acceptance Criteria:
* Acceptance Criteria 1: Admin should be able to log into the admin area and view the list of current recipes
* Acceptance Criteria 2: The admin dashboard should feature an action to add/remove featured
* Acceptance Criteria 3: Admin should be able to tick a recipe and turn the featured field on/off 
* Acceptance Criteria 4: This recipe should then appear on the index page as a featured recipe

### Tasks:
- [x] Add featured field to Recipe model in models.py
- [x] Add add_featured and remove_featured actions and methods into the RecipeAdmin class in admin.py
- [x] Add featured field into RecipeAdmin list display
- [x] Test functionality
