### ISSUE TITLE
USER STORY: View all recipes

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#43]
As a **user** I can **view all the recipes on one page** so that **I can browse all the recipes in one list**

### Acceptance Criteria:
* Acceptance Criteria 1: A 'view all recipes' button link should appear after each recipe list on the index page
* Acceptance Criteria 2: When clicked, the link should open the 'all recipes' page
* Acceptance Criteria 3: All recipes should be displayed as cards in a paginated list 

### Tasks:
- [ ] Create AllRecipes class view in views.py
- [ ] Add the URL path for the AllRecipes view in urls.py
- [ ] Create the all_recipes template with content, styling and logic
- [ ] Add URL links from the index template to the all_recipes template
- [ ] Test functionality
