### ISSUE TITLE
USER STORY: View other users profiles

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#6]
As a **user** I can **view other users profiles** so that **find out their details and connect with them on other platforms**

### Acceptance Criteria:
* Acceptance Criteria 1: A user should be able to click on an author displayed on a recipe or a comment poster to view their profile
* Acceptance Criteria 2: A user should be able to search for a username and open their profile
* Acceptance Criteria 3: If a user has chosen to add their details to the account, the user should be able to view the users details on the account profile page

### Tasks:
- [ ] Add UserProfile class view to views.py
- [ ] Add URL path for UserProfile view in urls.py
- [ ] Create user_profile template with content, logic and styling
- [ ] Add URL links to user profiles on recipe_details template comments and on all public recipes on index template and my_favourites template
- [ ] Test functionality
