### ISSUE TITLE
USER STORY: Edit or delete personal details 

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#7]
As a **user** I can **edit or delete my personal details on my account** so that **I can update my details or remove them**

### Acceptance Criteria:
* Acceptance Criteria 1: An edit button and a separate delete button should appear on the user account details page
* Acceptance Criteria 2: The edit button should open a pre-populated form which displays the user details 
* Acceptance Criteria 3: The edit form fields should be editable and on form submission the page should refresh with the new details updated on the account details page
*  Acceptance Criteria 4: The delete button should open a pop up window which asks the user to confirm that they wish to delete their profile details
* Acceptance Criteria 5: The user can cancel the deletion and return to the account details page, or confirm the deletion and the page should refresh and display the empty account details

### Tasks:
- [ ] Add custom User model class to models.py 
- [ ] Add UserForm class to forms.py 
- [ ] Import UserForm to views.py
- [ ] Add AccountDetails class view with logic and import UserForm 
- [ ] Add URL path for AccountDetails in urls.py
- [ ] Create account_details template and add form, logic and styling
- [ ] Add URL links to account_details template to base template navigation menus 
- [ ] Test functionality
