### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/viva-la-nacho#9]
As a **user** I can **delete my account** so that **I can remove my profile and all my recipes quickly and easily**

### Acceptance Criteria:
* Acceptance Criteria 1: A delete account button should appear to a logged in user in the account details page
* Acceptance Criteria 2: Clicking the button should open a pop up window asking the user to confirm their decision to delete their profile and warning them that the process cannot be undone
* Acceptance Criteria 3: Clicking the go back button will return the user to the account details page and cancel the deletion
* Acceptance Criteria 4: Clicking the delete account button should log the user out, delete the user and redirect them to the home page

### Tasks:
- [ ] Add DeleteAccount class view to views.py
- [ ] Add URL path for DeleteAccount view to urls.py
- [ ] Add delete button link to account_details template with URL
- [ ] Add confirmation pop-up to confirm users action
- [ ] Add styling and content for new features to account_details template
- [ ] Test functionality
